### ISSUE TITLE
jenkins_job creation fails with 400 "Bad Request" error on jenkins-cli.jar download

### ISSUE THREAD

**Issue by ianrossi** [chef-cookbooks/jenkins#392]
I'm using Chef 12.3 with the `jenkins` cookbook from the supermarket and a `jenkins_job` block has failed consistently when a `wget` or `curl` command to the same URL are consistently successful from the same machine. Here is the error and the `/var/chef/cache/chef-stacktrace.out` below. I've Googled quite a bit with no hints. Any ideas?

```
  * remote_file[/var/chef/cache/jenkins-cli.jar] action create[2015-08-06T15:35:18-04:00] WARN: remote_file[/var/chef/cache/jenkins-cli.jar] cannot be downloaded from http://localhost:8080/jnlpJars/jenkins-cli.jar: 400 "Bad Request"                                                                           [11/1805]


      ================================================================================
      Error executing action `create` on resource 'remote_file[/var/chef/cache/jenkins-cli.jar]'
      ================================================================================

      Net::HTTPServerException
      ------------------------
      400 "Bad Request"

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:394:in `ensure_cli_present!'
      /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:62:in `executor'
      /var/chef/cache/cookbooks/jenkins/libraries/job.rb:211:in `current_job'
      /var/chef/cache/cookbooks/jenkins/libraries/job.rb:87:in `load_current_resource'

      Compiled Resource:
      ------------------
      # Declared in 

      remote_file("/var/chef/cache/jenkins-cli.jar") do
        provider Chef::Provider::RemoteFile
        action "create"
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        path "/var/chef/cache/jenkins-cli.jar"
        atomic_update true
        source ["http://localhost:8080/jnlpJars/jenkins-cli.jar"]
        use_etag true
        use_last_modified true
        mode "0755"
      end


    ================================================================================
    Error executing action `create` on resource 'jenkins_job[dvs_shipments_api]'
    ================================================================================

    Net::HTTPServerException
    ------------------------
    remote_file[/var/chef/cache/jenkins-cli.jar] (dynamically defined) had an error: Net::HTTPServerException: 400 "Bad Request"

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:394:in `ensure_cli_present!'
    /var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:62:in `executor'
    /var/chef/cache/cookbooks/jenkins/libraries/job.rb:211:in `current_job'
    /var/chef/cache/cookbooks/jenkins/libraries/job.rb:87:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/fit-jenkins/recipes/jobs.rb

     25:   jenkins_job "#{app}_api" do
     26:     config api_xml
     27:   end
     28: 

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/fit-jenkins/recipes/jobs.rb:25:in `block in from_file'

    jenkins_job("dvs_shipments_api") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :jenkins_job
      cookbook_name "fit-jenkins"
      recipe_name "jobs"
      config "/var/chef/cache/dvs_shipments_api_config.xml"
    end
```

And `/var/chef/cache/chef-stacktrace.out`

```
Generated at 2015-08-06 15:35:22 -0400
Net::HTTPServerException: jenkins_job[dvs_shipments_api] (fit-jenkins::jobs line 25) had an error: Net::HTTPServerException: remote_file[/var/chef/cache/jenkins-cli.jar] (dynamically defined) had an error: Net::HTTPServerException: 400 "Bad Request"
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:179:in `streaming_request'
/opt/chef/embedded/apps/chef/lib/chef/provider/remote_file/http.rb:60:in `fetch'
/opt/chef/embedded/apps/chef/lib/chef/provider/remote_file/content.rb:64:in `grab_file_from_uri'
/opt/chef/embedded/apps/chef/lib/chef/provider/remote_file/content.rb:49:in `try_multiple_sources'
/opt/chef/embedded/apps/chef/lib/chef/provider/remote_file/content.rb:38:in `file_for_provider'
/opt/chef/embedded/apps/chef/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
/opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:459:in `tempfile'
/opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:337:in `do_generate_content'
/opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:148:in `action_create'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:130:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
/var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:394:in `ensure_cli_present!'
/var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:62:in `executor'
/var/chef/cache/cookbooks/jenkins/libraries/job.rb:211:in `current_job'
/var/chef/cache/cookbooks/jenkins/libraries/job.rb:87:in `load_current_resource'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:113:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>'
```

**Comment by ianrossi** [comment]
@schisamo Any ideas?

**Comment by ianrossi** [comment]
Update: The Chef run still fails with the error I originally posted in this issue. However, the jobs are eventually created successfully. I haven't figured out why yet (perhaps subsequent Chef runs). Still, when I run `chef-client` on the Jenkins server, the Chef run fails with the same error. If anyone can shed light on this, it's much appreciated. Let me know if I can provide any more information.

**Comment by ianrossi** [comment]
This is still an issue for me. While I can make changes to my Jenkins jobs and expect that they will appear the next day, I can't make a change to me jobs recipe and apply those changes immediately because manual Chef runs fail with this error. Any info or help would be much appreciated. Thanks.

**Comment by shaneramey** [comment]
I had a similar problem (though my error was a 403 Forbidden) when using an http_proxy: setting in my .kitchen.yml. When I removed that, the problem went away.

**Comment by cheeseplus** [comment]
This seems to be have been a point in time issue with specific versions of Jenkins. Please open a new issue if this behaviour has resurfaced.
