### ISSUE TITLE
Running Jenkins cookbook from another cookbook fails, while adding jenkins recipe to the provisioner works

### ISSUE THREAD

**Issue by svscorp** [chef-cookbooks/jenkins#408]
Hi,

I am using Ubuntu 15.04, latest Chef, Vagrant and Ruby. Having issues with running jenkins coobook from my cookbook . Trying to build my cookbook when one of the recipes will be Jenkins installation. I have Vagrant configured: 

````
# Vagrantfile
config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "/home/user/chef/cookbooks"
    chef.add_recipe("my-cookbook")
  end
````

Default recipe
````
# cookbooks/my-cookbook/recipes/default.rb
include_recipe 'apt::default'
include_recipe 'jenkins::master'
````

Attributes:
````
# cookbooks/my-cookbook/attributes/default.rb
default['jenkins']['master']['install_method'] = 'package'
````

And when I run vagrant up, cookbook fails with the output below:
````
# chef-solo output
==> default: * execute[apt-get-update-periodic] action run
==> default:  (skipped due to only_if)
==> default:   
==> default: * directory[/var/cache/local] action create
==> default:  (up to date)
==> default:   
==> default: * directory[/var/cache/local/preseeding] action create
==> default:  (up to date)
==> default: Recipe: jenkins::_master_package
==> default:   
==> default: * apt_repository[jenkins] action add
==> default:     
==> default: 
==> default:     
==> default: ================================================================================
==> default:     
==> default: Error executing action `add` on resource 'apt_repository[jenkins]'
==> default:     
==> default: ================================================================================
==> default:     
==> default: 
==> default: 
==> default:     
==> default: NoMethodError
==> default:     
==> default: -------------
==> default:     
==> default: undefined method `start_with?' for nil:NilClass
==> default:     
==> default: 
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /tmp/vagrant-chef/9b182a6df716253a90e155468f4a5b1c/cookbooks/apt/providers/repository.rb:198:in `block in class_from_file'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /tmp/vagrant-chef/9b182a6df716253a90e155468f4a5b1c/cookbooks/jenkins/recipes/_master_package.rb
==> default:     
==> default:      28:   apt_repository 'jenkins' do
==> default:      29:     uri          node['jenkins']['master']['repository']
==> default:      30:     distribution 'binary/'
==> default:      31:     key          node['jenkins']['master']['repository_key']
==> default:      32:     unless node['jenkins']['master']['repository_keyserver'].nil?
==> default:      33:       keyserver    node['jenkins']['master']['repository_keyserver']
==> default:      34:     end
==> default:      35:   end
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /tmp/vagrant-chef/9b182a6df716253a90e155468f4a5b1c/cookbooks/jenkins/recipes/_master_package.rb:28:in `from_file'
==> default:     
==> default:     apt_repository("jenkins") do
==> default:       action :add
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :apt_repository
==> default:       cookbook_name :jenkins
==> default:       recipe_name "_master_package"
==> default:       distribution "binary/"
==> default:     end
==> default:     
==> default: [2015-09-27T17:47:07+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2015-09-27T17:47:07+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2015-09-27T17:47:07+00:00] ERROR: Exception handlers complete
````

But when I include it in Vagrantfile, it installs/starts jenkins:
````
# Vagrantfile
config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "/home/user/chef/cookbooks"
    chef.add_recipe("my-cookbook")
    chef.add_recipe("jenkins")
  end
````

Can you assist where did my path go wrong? Thanks in advance :)

**Comment by svscorp** [comment]
Hm, dependency was missing in ````metadata.rb```` (````depends 'jenkins', '~> 2.4.1'````)
