### ISSUE TITLE
jenkins_ssh_slave ambiguous method overloading

### ISSUE THREAD

**Issue by onknows** [chef-cookbooks/jenkins#435]
Using 2.4.1 of cookbook when I use `jenkins_ssh_slave` for example

```
jenkins_ssh_slave 'myslave' do
  remote_fs 'C:\jenkins'
  labels ['myslave'] 
  host        '192.168.0.100'
  user        'vagrant'
  credentials 'secret'
end
```

This results in error message

```
==> default: [2015-12-12T08:42:23+00:00] ERROR: jenkins_ssh_slave[rmc] (jenkins::ssh_slave line 2) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
==> default: ---- Begin output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20151212-3819-1c6azgj ----
==> default: STDOUT: 
==> default: STDERR: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method hudson.plugins.sshslaves.SSHLauncher#<init>.
==> default: Cannot resolve which method to invoke for [class java.lang.String, class java.lang.Integer, null, null, null, null, null] due to overlapping prototypes between:
```

**Comment by ostraaten** [comment]
This install btw Jenkins 1.641

**Comment by zanshin** [comment]
I, too, am seeing the ambiguous method overload error when using the jenkins_ssh_slave resource. Any workarounds?

**Comment by ravibhure** [comment]
Same errors, any fix ?

``` 
        Cookbook Trace:
         ---------------
         /tmp/kitchen/cache/cookbooks/jenkins/libraries/_executor.rb:84:in `execute!'
         /tmp/kitchen/cache/cookbooks/jenkins/libraries/_executor.rb:137:in `groovy!'
         /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave.rb:149:in `block in action_create'
         /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave.rb:148:in `action_create'

         Resource Declaration:
         ---------------------
         # In /tmp/kitchen/cache/cookbooks/jenkins-cookbook/recipes/slave.rb

          28: jenkins_ssh_slave jenkins_slave do
          29:   description 'A mgmt host tester, but over SSH'
          30:   remote_fs   "/home/#{slave_user}"
          31:   labels      %w(runner fast)
          32:   user        slave_user
          33:   # SSH specific attributes
          34:   host        jenkins_slave
          35:   credentials slave_pass
          36: end
          37:

         Compiled Resource:
         ------------------
         # Declared in /tmp/kitchen/cache/cookbooks/jenkins-cookbook/recipes/slave.rb:28:in `from_file'

         jenkins_ssh_slave("10.0.15.10") do
           action [:create]
           retries 0
           retry_delay 2
           default_guard_interpreter :default
           declared_type :jenkins_ssh_slave
           cookbook_name "jenkins-cookbook"
           recipe_name "slave"
           description "A mgmt host tester, but over SSH"
           remote_fs "/home/ubuntu"
           labels ["runner", "fast"]
           user "ubuntu"
           host "10.0.15.10"
           credentials "ubuntu"
           slave_name "10.0.15.10"
           usage_mode "normal"
         end


     Running handlers:
     [2016-02-16T06:53:19+00:00] ERROR: Running exception handlers
     Running handlers complete
     [2016-02-16T06:53:19+00:00] ERROR: Exception handlers complete
     Chef Client failed. 9 resources updated in 01 minutes 36 seconds
     [2016-02-16T06:53:19+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
     [2016-02-16T06:53:19+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
     [2016-02-16T06:53:19+00:00] ERROR: jenkins_ssh_slave[10.0.15.10] (jenkins-cookbook::slave line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
     ---- Begin output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20160216-11578-167kv61 --username "admin" --password "admin" ----
     STDOUT:
     STDERR: Unexpected exception occurred while performing groovy command!
     groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method hudson.plugins.sshslaves.SSHLauncher#<init>.
     Cannot resolve which method to invoke for [class java.lang.String, class java.lang.Integer, null, null, null, null, null] due to overlapping prototypes between:
      [class java.lang.String, int, interface com.cloudbees.jenkins.plugins.sshcredentials.SSHUser, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String]
      [class java.lang.String, int, interface com.cloudbees.plugins.credentials.common.StandardUsernameCredentials, class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String]
      at groovy.lang.MetaClassImpl.chooseMostSpecificParams(MetaClassImpl.java:2922)
      at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:2875)
      at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:2816)
      at groovy.lang.MetaClassImpl.createConstructorSite(MetaClassImpl.java:3065)
      at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:75)
      at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
      at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
      at RemoteClass.run(RemoteClass:64)
     stOrRunnable(GroovyShell.java:266)
      at groovy.lang.GroovyShell.run(GroovyShell.java:517)
      at hudson.cli.GroovyCommand.run(GroovyCommand.java:86)
      at hudson.cli.CLICommand.main(CLICommand.java:238)
      at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:608)
      at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:583)
      at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:542)
      at hudson.remoting.UserRequest.perform(UserRequest.java:120)
      at hudson.remoting.UserRequest.perform(UserRequest.java:48)
      at hudson.remoting.Request$2.run(Request.java:326)
      at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
      at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
      at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
      at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
      at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
      at java.lang.Thread.run(Thread.java:745)
     ---- End output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20160216-11578-167kv61 --username "admin" --password "admin" ----
     Ran "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20160216-11578-167kv61 --username "admin" --password "admin" returned 255
     [2016-02-16T06:53:20+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-geerlingguy-centos6>.
>>>>>> Please see .kitchen/logs/default-geerlingguy-centos6.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------
```

**Comment by cheeseplus** [comment]
Make sure so use a jenkins_credential resource prior to calling `jenkins_ssh_slave`. Closing this one out but please open against current versions if still stuck.
