### ISSUE TITLE
Errno::EAFNOSUPPORT creating job with jenkins_job

### ISSUE THREAD

**Issue by kbaltrinic** [chef-cookbooks/jenkins#458]
We have a cookbook that uses the jenkins cookbook to create/maintain our jenkins masters.  It has been working fine for quite a while, though it has been a few months since we last used it to actually create a new master.   Now when creating a new machine (the only time the jenkins_job resource is not 'up to date') we are getting the following error.  This is occurring on Centos 6.6 and chef-client 12.7.2. 

```
Errno::EAFNOSUPPORT: jenkins_job[create-chef-job] (jenkins-chef-cvent::_create-chef-job-creator-job line 22) had an error: Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2) for "localhost" port 8080

/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
/opt/chefdk/embedded/lib/ruby/2.1.0/open-uri.rb:313:in `open_http'
/opt/chefdk/embedded/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
/opt/chefdk/embedded/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
/opt/chefdk/embedded/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
/opt/chefdk/embedded/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
/opt/chefdk/embedded/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
/opt/chefdk/embedded/lib/ruby/2.1.0/open-uri.rb:704:in `open'
/opt/chefdk/embedded/lib/ruby/2.1.0/open-uri.rb:34:in `open'
/var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:361:in `block in wait_until_ready!'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:101:in `call'
/opt/chefdk/embedded/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:359:in `wait_until_ready!'
/var/chef/cache/cookbooks/jenkins/libraries/_helper.rb:61:in `executor'
/var/chef/cache/cookbooks/jenkins/libraries/job.rb:211:in `current_job'
/var/chef/cache/cookbooks/jenkins/libraries/job.rb:87:in `load_current_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider.rb:127:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource.rb:596:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:73:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:104:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:668:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:663:in
```

**Comment by cheeseplus** [comment]
Given the age and version changes I'm going to close this one. I suspect it had to do with either another service or an IPv6 configuration issue. Feel free to open a new issue if this is still present in modern versions.
