### ISSUE TITLE
Jenkins 2.11 CLI authentication (auth enabled)

### ISSUE THREAD

**Issue by jharshman** [chef-cookbooks/jenkins#488]
### Cookbook version
2.6.0

### Chef-client version
12.11.18

### Platform Details
Ubuntu 14.04 LTS
Jenkins 2.11

### Scenario:
Once authentication is configured (in my case LDAP) subsequent runs of the cookbook against the target error while attempting to install plugins ( or any cli related activity ) errors.  This even occurs if a jenkins user has been setup with key authentication.

### Steps to Reproduce:
1. run cookbook, install plugins
2. configure auth
3. add another plugin to list
4. re-execute cookbook

### Expected Result:
Expected result would be that the cli is authenticated to and plugins and other cli functions get processed correctly.

### Actual Result:
Run results in a 255 error and the following output:
```
Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '255'
           ---- Begin output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" install-plugin /tmp/kitchen/cache/icon-shim-2.0.3.plugin -name icon-shim  ----
           STDOUT: 
           STDERR: java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]
                at hudson.cli.CLI.getCliTcpPort(CLI.java:284)
                at hudson.cli.CLI.<init>(CLI.java:128)
                at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
                at hudson.cli.CLI._main(CLI.java:473)
                at hudson.cli.CLI.main(CLI.java:384)
                Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli
                        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
                        at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
                        at hudson.cli.CLI.connectViaHttp(CLI.java:152)
                        at hudson.cli.CLI.<init>(CLI.java:132)
                        ... 3 more
           ---- End output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" install-plugin /tmp/kitchen/cache/icon-shim-2.0.3.plugin -name icon-shim  ----
           Ran "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" install-plugin /tmp/kitchen/cache/icon-shim-2.0.3.plugin -name icon-shim  returned 255
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/_executor.rb:85:in `execute!'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:316:in `install_plugin_from_url'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:288:in `install_plugin_from_update_center'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:279:in `block in install_plugin_from_update_center'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `each'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `install_plugin_from_update_center'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:123:in `block (2 levels) in <class:JenkinsPlugin>'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:153:in `block in <class:JenkinsPlugin>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/jenkins20/recipes/_plugins.rb
            50:   jenkins_plugin plugin
            51: end
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/jenkins20/recipes/_plugins.rb:50:in `block in from_file'
           jenkins_plugin("matrix-auth") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_plugin
             cookbook_name "jenkins20"
             recipe_name "_plugins"
             install_deps true
           end
           Platform:
           ---------
           x86_64-linux
       Running handlers:
       [2016-07-08T18:21:14+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-07-08T18:21:14+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 05 seconds
       [2016-07-08T18:21:14+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-07-08T18:21:14+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-07-08T18:21:14+00:00] ERROR: jenkins_plugin[matrix-auth] (jenkins20::_plugins line 50) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
       ---- Begin output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" install-plugin /tmp/kitchen/cache/icon-shim-2.0.3.plugin -name icon-shim  ----
       STDOUT: 
       STDERR: java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]
        at hudson.cli.CLI.getCliTcpPort(CLI.java:284)
        at hudson.cli.CLI.<init>(CLI.java:128)
        at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
        at hudson.cli.CLI._main(CLI.java:473)
        at hudson.cli.CLI.main(CLI.java:384)
        Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
                at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
                at hudson.cli.CLI.connectViaHttp(CLI.java:152)
                at hudson.cli.CLI.<init>(CLI.java:132)
                ... 3 more
       ---- End output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" install-plugin /tmp/kitchen/cache/icon-shim-2.0.3.plugin -name icon-shim  ----
       Ran "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" install-plugin /tmp/kitchen/cache/icon-shim-2.0.3.plugin -name icon-shim  returned 255
       [2016-07-08T18:21:14+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <server-ubuntu-trusty64>.  Please see .kitchen/logs/server-ubuntu-trusty64.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Here is a more concise example of the error when executed directly from console.
```
vagrant@server-ubuntu-trusty64:~$ sudo java -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080/jenkins -i "/tmp/kitchen/cache/jenkins-key" install-plugin /tmp/kitchen/cache/workflow-api-2.1.plugin -name workflow-api
java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]
        at hudson.cli.CLI.getCliTcpPort(CLI.java:284)
        at hudson.cli.CLI.<init>(CLI.java:128)
        at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
        at hudson.cli.CLI._main(CLI.java:473)
        at hudson.cli.CLI.main(CLI.java:384)
        Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/jenkins/cli
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
                at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
                at hudson.cli.CLI.connectViaHttp(CLI.java:152)
                at hudson.cli.CLI.<init>(CLI.java:132)
                ... 3 more
``` 

~~The issue also occurs when using the run_context `jenkins_username` and `jenkins_password` values.~~
edit: It appears those values are only for PAM auth which is not configured.

Any help on this issue would be great, been hitting my head against a wall trying to work this one out.

Thanks in advance!

**Comment by jharshman** [comment]
There needs to be a method of authenticating once the cookbook has run through once.  Putting together some hacky code to disable security before the rest of the cookbook runs isn't a good fix :'(

**Comment by gawbul** [comment]
I'm hitting this issue too... I've tried increasing `retries` count and `retry_delay` for `jenkins_job` and `jenkins_plugin` as a workaround, but without success. Have you got any further with this?

**Comment by jharshman** [comment]
yeah no luck on my end, currently I have it disable security entirely by rewriting the config.xml as a preliminary step before each run.  But that solution isn't sustainable in the long run.

**Comment by jharshman** [comment]
also fails when using the jenkins local user database

**Comment by jharshman** [comment]
with AD auth enabled & binding user to public key as suggested in the README.
i.e:
on master: 
```
jenkins_user 'joshua' do
  public_keys [public_key]
end
```
on slave:
```
node.override['jenkins']['master']['endpoint']=master
node.run_state[:jenkins_private_key] = bag['privkey']
jenkins_ssh_slave node['hostname'] do
  ...
  ...
end
```

```
java -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://192.168.121.10:8080 -i "/tmp/kitchen/cache/jenkins-key" groovy /tmp/groovy20160726-14229-j4xm4p
java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]
	at hudson.cli.CLI.getCliTcpPort(CLI.java:284)
	at hudson.cli.CLI.<init>(CLI.java:128)
	at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
	at hudson.cli.CLI._main(CLI.java:473)
	at hudson.cli.CLI.main(CLI.java:384)
	Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://192.168.121.10:8080/cli
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
		at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
		at hudson.cli.CLI.connectViaHttp(CLI.java:152)
		at hudson.cli.CLI.<init>(CLI.java:132)
		... 3 more
```

works fine when authentication is completely disabled.

**Comment by jharshman** [comment]
alright so the fix here is to set the TCP port for JNLP agents to either fixed or random.
Go to Manage Jenkins -> Configure Global Security -> "TCP port for JNLP agents"

I chose random and now I can authenticate with an existing AD user.  So I just need to create a special AD user for Jenkins and should be good to go.

@gawbul Im going to close this issue, your issue looks a it different and probably should have it's own issue number.
