### ISSUE TITLE
jenkins_plugin is not idempotent if installing plugin from hpi

### ISSUE THREAD

**Issue by lioramilbaum** [chef-cookbooks/jenkins#494]
### Cookbook version

2.6.0
### Chef-client version

12.12.15
### Platform Details

Ubuntu 12.04 AWS
### Scenario:

Installed a Jenkins plugin using hpi. Second time my custom recipe runs failing.
### Steps to Reproduce:

```
jenkins_plugin 'ibm-ucdeploy-publisher' do
  source "https://public.dhe.ibm.com/software/products/UrbanCode/plugins/ibmucd/Jenkins/ibm-ucdeploy-publisher-129.hpi"
  not_if do ::File.exists?("node['jenkins']['master']['home']}/plugins/ibm-ucdeploy-publisher.jpi") end
  notifies :restart, 'service[jenkins]', :immediately
end
```

Run it twice
### Expected Result:

Second run should do nothing. Plugin is installed in the first run.
### Actual Result:

```
- jenkins_plugin[ibm-ucdeploy-publisher] action install
  
   ================================================================================
   Error executing action `install` on resource 'jenkins_plugin[ibm-ucdeploy-publisher]'
   ================================================================================
  
   NoMethodError
  ---
  
   undefined method `[]' for nil:NilClass
  
   Cookbook Trace:
  ---
  
   /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:245:in `desired_version'
   /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:141:in`block in class:JenkinsPlugin'
   /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
  
   Resource Declaration:
  ---
  
   # In /var/chef/cache/cookbooks/depi_integrations/recipes/jenkins-ucd.rb
  
    14: jenkins_plugin 'ibm-ucdeploy-publisher' do
    15:   source "https://public.dhe.ibm.com/software/products/UrbanCode/plugins/ibmucd/Jenkins/ibm-ucdeploy-publisher-129.hpi"
    16:   not_if do ::File.exists?("node['jenkins']['master']['home']}/plugins/ibm-ucdeploy-publisher.jpi") end
    17:   notifies :restart, 'service[jenkins]', :immediately
    18: end
    19: 
  
   Compiled Resource:
  ---
  
   # Declared in /var/chef/cache/cookbooks/depi_integrations/recipes/jenkins-ucd.rb:14:in `from_file'
  
   jenkins_plugin("ibm-ucdeploy-publisher") do
     action [:install]
     retries 0
     retry_delay 2
     default_guard_interpreter :default
     declared_type :jenkins_plugin
     cookbook_name "depi_integrations"
     recipe_name "jenkins-ucd"
     source "https://public.dhe.ibm.com/software/products/UrbanCode/plugins/ibmucd/Jenkins/ibm-ucdeploy-publisher-129.hpi"
     not_if { #code block }
   end
  
   Platform:
  ---
  
   x86_64-linux
```

**Comment by LuneraSteve** [comment]
+1 This is still happening.

**Comment by cheeseplus** [comment]
This is part of the larger issue covered in https://github.com/chef-cookbooks/jenkins/issues/534 so eventually this may be closed as dupe just to reduce the noise around what is effectively the same root issue of plugin installation/idempotency with Jenkins is a pain.
