### ISSUE TITLE
groovy.lang.MissingPropertyException on jenkins_ssh_slave :create

### ISSUE THREAD

**Issue by zr2d2** [chef-cookbooks/jenkins#495]
### Cookbook version
2.6.0

### Chef-client version
 12.8.1

### Platform Details
Centos 6.8 in AWS

### Scenario:
trying to create a Jenkins SSH Slave results in a groovy MissingPropertyException

### Steps to Reproduce:
search for target slaves, accept their ssh fingerprint, and try to make them into a Jenkins slave.

directory "/jenkins"
search(:node, 'role:"apps_linux"').each { |apphost|
  if apphost.environment == "dev"
    apphost.deployment.servers["lnxapps"].each_pair { |svr, data|
      execute "ssh-keyscan #{data.private_ip_address} >> ~/.ssh/known_hosts" do
        not_if "grep #{data.private_ip_address} ~/.ssh/known_hosts"
        returns [0,1,255] # don't care too hard if this fails
      end
      jenkins_ssh_slave apphost.name.dup do
        host data.private_ip_address
        action :create
        remote_fs "/jenkins"
        labels ['Linux']
        user 'root'
        credentials 'root'
      end
    }
  end
}

### Expected Result:
slave process would be started on remote machine

### Actual Result:
* jenkins_ssh_slave[HOSTING-DEV-2015072917-SH-LNXAPPS-011] action create

    ================================================================================
    Error executing action `create` on resource 'jenkins_ssh_slave[HOSTING-DEV-2015072917-SH-LNXAPPS-011]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "/usr/lib/jvm/java/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8085 -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20160805-19358-12o3ibv ----
    STDOUT:
    STDERR: ERROR: Unexpected exception occurred while performing groovy command.
    groovy.lang.MissingPropertyException: No such property: host for class: hudson.slaves.JNLPLauncher
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
        at RemoteClass.run(RemoteClass:41)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
        at groovy.lang.GroovyShell.run(GroovyShell.java:518)
        at groovy.lang.GroovyShell.run(GroovyShell.java:497)
        at hudson.cli.GroovyCommand.run(GroovyCommand.java:86)
        at hudson.cli.CLICommand.main(CLICommand.java:257)
        at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:884)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:859)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:818)
        at hudson.remoting.UserRequest.perform(UserRequest.java:153)
        at hudson.remoting.UserRequest.perform(UserRequest.java:50)
        at hudson.remoting.Request$2.run(Request.java:332)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
        at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
        at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
        at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    ---- End output of "/usr/lib/jvm/java/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8085 -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20160805-19358-12o3ibv ----
    Ran "/usr/lib/jvm/java/bin/java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8085 -i "/var/chef/cache/jenkins-key" groovy /tmp/groovy20160805-19358-12o3ibv returned 1

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:85:in `execute!'
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:138:in `groovy!'
    /var/chef/cache/cookbooks/jenkins/libraries/slave.rb:318:in `current_slave'
    /var/chef/cache/cookbooks/jenkins/libraries/slave.rb:125:in `load_current_resource'
    /var/chef/cache/cookbooks/jenkins/libraries/slave_ssh.rb:74:in `load_current_resource'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/femadata-apps/recipes/jenkins.rb

     73:       jenkins_ssh_slave apphost.name.dup do
     74:         host data.private_ip_address
     75:         action :create
     76:         remote_fs "/jenkins"
     77:         labels ['Linux']
     78:         user 'root'
     79:         credentials 'root'
     80:       end
     81:     }

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/femadata-apps/recipes/jenkins.rb:73:in `block (2 levels) in from_file'

    jenkins_ssh_slave("HOSTING-DEV-2015072917-SH-LNXAPPS-011") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :jenkins_ssh_slave
      cookbook_name "femadata-apps"
      recipe_name "jenkins"
      host "10.20.12.37"
      remote_fs "/jenkins"
      labels ["Linux"]
      user "root"
      credentials "root"
      slave_name "HOSTING-DEV-2015072917-SH-LNXAPPS-011"
    end

**Comment by damacus** [comment]
Closing this issue as stale. It was opened in 2016 with CentOS 6.8 (EOL) and Chef 12.8.1 (EOL). The cookbook has undergone significant changes since then. If this is still a problem with the current version of the cookbook, please open a new issue with updated details.
