### ISSUE TITLE
jenkins-cli download fails

### ISSUE THREAD

**Issue by jmaass** [chef-cookbooks/jenkins#500]
### Cookbook version
2.6.0

### Chef-client version
12.12.15

### Platform Details
Centos 7 (3.10.0-327.22.2.el7.x86_64)
### Scenario:
Installing a Jenkins Server (V2.17) with the following cookbook and attributes
### Steps to Reproduce:
```Cookbook:
include_recipe 'role_default'
include_recipe 'jenkins-repo'
include_recipe 'java'

plugins = [ 'active-directory',
            'artifactory',	
            'build-timeout',
            'build-blocker-plugin',
            'buildgraph-view',
            'build-monitor-plugin ',
            'cobertura',
            'config-file-provider',
            'copyartifact',
            'credentials-binding',
            'credentials',
            'cucumber-reports',
            'dashboard-view',
            'durable-task',
            'email-ext',
            'external-monitor-job',
            'xfpanel',
            'cloudbees-folder',
            'gatling',
            'git-client',
            'git',
            'greenballs',
            'http_request',
            'javadoc',
            'join',
            'jquery',	
            'junit',
            'ldap',
            'mailer',
            'matrix-auth',
            'matrix-project',
            'maven-dependency-update-trigger',
            'maven-plugin',
            'Maven Integration plugin',
            'maven-metadata-plugin',
            'nodelabelparameter',
            'antisamy-markup-formatter',
            'parameterized-trigger',
            'workflow-aggregator',
            'workflow-api',
            'workflow-basic-steps',
            'workflow-basic-steps',
            'workflow-cps',
            'pipeline-input-step',
            'workflow-job',
            'workflow-multibranch',
            'workflow-durable-task-step',
            'workflow-scm-step',
            'workflow-cps-global-lib',
            'pipeline-stage-step',
            'pipeline-stage-view',
            'workflow-step-api',
            'workflow-support',
            'plain-credentials',
            'publish-over-ssh',
            'rebuild',
            'repository-connector',
            'scm-api',
            'script-security',
            'scriptler',
            'sectioned-view',
            'sonar',
            'ssh-credentials',
            'ssh-slaves',
            'analysis-core',
            'structs',
            'subversion',
            'testng-plugin',
            'throttle-concurrents',
            'timestamper',
            'token-macro',
            'view-job-filters',
            'ws-cleanup'
          ]

group 'jenkins' do
  system true
  append true
  gid '11119'
end

user 'jenkins' do
  comment 'Jenkins Server'
  system  true
  manage_home true
  shell   '/bin/false'
  uid     '11119'
  group     'jenkins'
end

include_recipe 'jenkins::master'

plugins.each do | plugin |
  jenkins_plugin plugin do
    action [ :install, :enable ]
    notifies :restart, 'service[jenkins]', :delayed
  end
end
```

Attributes:

```
default['java']['jdk_version'] = '8'
default['java']['set_etc_environment'] = true
default['jenkins']['master']['install_method'] = 'package'
default['jenkins']['executor']['timeout'] = 300
default['jenkins']['master']['home'] = '/opt/jenkins'
default['jenkins']['master']['jvm_options'] = '-Dhudson.diyChunking=false -Djenkins.install.runSetupWizard=false'
```

### Expected Result:
The Jenkins Server and the plugins get installed

### Actual Result:
         * jenkins_plugin[active-directory] action install
         Recipe: <Dynamically Defined Resource>
           * remote_file[/tmp/kitchen/cache/update-center.json] action create
             - create new file /tmp/kitchen/cache/update-center.json
             - update content in file /tmp/kitchen/cache/update-center.json from none to ef3aaa
             - suppressed sensitive resource
             - change mode from '' to '0644'
             - restore selinux security context
           * file[/tmp/kitchen/cache/extracted-update-center.json] action create
             - create new file /tmp/kitchen/cache/extracted-update-center.json
             - update content in file /tmp/kitchen/cache/extracted-update-center.json from none to 21b59e
             - suppressed sensitive resource
             - change mode from '' to '0644'
             - restore selinux security context
           * remote_file[/tmp/kitchen/cache/mailer-1.5.plugin] action create
             - create new file /tmp/kitchen/cache/mailer-1.5.plugin
             - update content in file /tmp/kitchen/cache/mailer-1.5.plugin from none to 5257d7
             (new content is binary, diff output suppressed)
             - restore selinux security context
           * remote_file[/tmp/kitchen/cache/jenkins-cli.jar] action create[2016-08-10T15:38:37+02:00] WARN: remote_file[/tmp/kitchen/cache/jenkins-cli.jar] cannot be downloaded from http://localhost:8080/jnlpJars/jenkins-cli.jar: 503 "Service Unavailable"

             ================================================================================
             Error executing action `create` on resource 'remote_file[/tmp/kitchen/cache/jenkins-cli.jar]'
             ================================================================================

             Net::HTTPFatalError
             -------------------
             503 "Service Unavailable"

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:436:in `ensure_cli_present!'
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:62:in `executor'
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:316:in `install_plugin_from_url'
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:288:in `install_plugin_from_update_center'
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:279:in `block in install_plugin_from_update_center'
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `each'
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `install_plugin_from_update_center'
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:123:in `block (2 levels) in <class:JenkinsPlugin>'
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:153:in `block in <class:JenkinsPlugin>'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

             Compiled Resource:
             ------------------
             # Declared in

             remote_file("/tmp/kitchen/cache/jenkins-cli.jar") do
        provider Chef::Provider::RemoteFile
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        source ["http://localhost:8080/jnlpJars/jenkins-cli.jar"]
        use_etag true
        use_last_modified true
        mode "0755"
        atomic_update true
        path "/tmp/kitchen/cache/jenkins-cli.jar"
             end

             Platform:
             ---------
             x86_64-linux

           ================================================================================
           Error executing action `install` on resource 'jenkins_plugin[active-directory]'
           ================================================================================

           Net::HTTPFatalError
           -------------------
           remote_file[/tmp/kitchen/cache/jenkins-cli.jar] (dynamically defined) had an error: Net::HTTPFatalError: 503 "Service Unavailable"

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:436:in `ensure_cli_present!'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:62:in `executor'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:316:in `install_plugin_from_url'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:288:in `install_plugin_from_update_center'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:279:in `block in install_plugin_from_update_center'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `each'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:272:in `install_plugin_from_update_center'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:123:in `block (2 levels) in <class:JenkinsPlugin>'
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:153:in `block in <class:JenkinsPlugin>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/default.rb

           123:   jenkins_plugin plugin do
           124:     action [ :install, :enable ]
           125:     notifies :restart, 'service[jenkins]', :delayed
           126:   end
           127: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/default.rb:123:in `block in from_file'

           jenkins_plugin("active-directory") do
             action [:install, :enable]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_plugin
             cookbook_name "mnet_jenkins"
             recipe_name "default"
             install_deps true
           end

           Platform:
           ---------
           x86_64-linux

       Running handlers:
       [2016-08-10T15:38:37+02:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-08-10T15:38:37+02:00] ERROR: Exception handlers complete
       Chef Client failed. 11 resources updated in 42 seconds
       [2016-08-10T15:38:37+02:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-08-10T15:38:37+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-08-10T15:38:37+02:00] ERROR: jenkins_plugin[active-directory] (mnet_jenkins::default line 123) had an error: Net::HTTPFatalError: remote_file[/tmp/kitchen/cache/jenkins-cli.jar] (dynamically defined) had an error: Net::HTTPFatalError: 503 "Service Unavailable"
       [2016-08-10T15:38:37+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

The host on which Jenkins gets installed is behind a firewall and needs to go over a proxy in order to download plugins. However, this is not true for Jenkins-cli.jar since it is present on the node and can be downloaded successfully with curl:

```
[chefinit@centos7 ~]$ curl http://localhost:8080/jnlpJars/jenkins-cli.jar >> /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  817k  100  817k    0     0  33.7M      0 --:--:-- --:--:-- --:--:-- 36.2M
```
There are no errors in the jenkins.log and proxies are not configured on the system.

**Comment by jmaass** [comment]
We've drawn a tcpdump on lo1.
[chef_remotefile_01.zip](https://github.com/chef-cookbooks/jenkins/files/411404/chef_remotefile_01.zip)

**Comment by jmaass** [comment]
Error on our side, with the corrected configuration it works like a charm! Beware your proxy settings at unlikely locations!
