### ISSUE TITLE
SSH Credentials Plugin 1.13 breaks cookbook

### ISSUE THREAD

**Issue by docwhat** [chef-cookbooks/jenkins#561]
### Cookbook version

4.2.1

### Chef-client version

12.17.44

### Platform Details

RHEL/CentOS v6 or v7

### Scenario:

The `jenkins_private_key_credentials` resource fails on a second run (when it would check if it needs to update or not).

### Steps to Reproduce:

``` .rb
jenkins_private_key_credentials "myuser" do
      id "myuser-ssh-slave-key"
      description "Myuser Slave"
      private_key "sekret"
end
```

### Expected Result:

It should both create and update the credential "myuser-ssh-slave-key".

### Actual Result:

It creates the credential fine, but crashes on the second run (updating).  This is true if nothing changes or not.

```
    STDERR: ERROR: Unexpected exception occurred while performing groovy command.
    java.lang.NullPointerException: Cannot get property 'plainText' on null object
        at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
        at RemoteClass.run(RemoteClass:38)
        at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
        at groovy.lang.GroovyShell.run(GroovyShell.java:518)
        at groovy.lang.GroovyShell.run(GroovyShell.java:497)
        at hudson.cli.GroovyCommand.run(GroovyCommand.java:86)
        at hudson.cli.CLICommand.main(CLICommand.java:264)
        at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:93)
        at sun.reflect.GeneratedMethodAccessor781.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:894)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:869)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:828)
        at hudson.remoting.UserRequest.perform(UserRequest.java:153)
        at hudson.remoting.UserRequest.perform(UserRequest.java:50)
        at hudson.remoting.Request$2.run(Request.java:336)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
        at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:64)
        at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
        at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I'm pretty sure this broke when I updated the [SSH Credentials Plugin](https://wiki.jenkins-ci.org/display/JENKINS/SSH+Credentials+Plugin) to 1.13 because it is the only credentials related plugin I updated this week.

The [Credentials plugin](https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin) was updated a week or two before this.

**Comment by docwhat** [comment]
I think it was broken by [commit b2904](https://github.com/jenkinsci/ssh-credentials-plugin/commit/b2904ed5b55e50f88e0dbde11bf615e25f622a01) in the SSH Credentials Plugin, since none of these keys have passphrases.

**Comment by ramc-n** [comment]
I am also facing this issue in our production servers, since few days. Thank you for submitting this issue @docwhat

**Comment by ehaselwanter** [comment]
me too. pinned the jenkins plugin to 1.12 for now

**Comment by bhipple** [comment]
Also ran into this issue, on Ubuntu 16.04 with Jenkins 2.47.  Pinning to 1.12 fixed it for me as well.  Thanks for the heads up.

Looks like they're aware of the issue upstream:
https://issues.jenkins-ci.org/browse/JENKINS-42280

**Comment by cheeseplus** [comment]
Closing this one as it's an upstream issue but it'll still be searchable for folks trying to hunt it down.

**Comment by docwhat** [comment]
For all the people with this issue, please up vote [JENKINS-42280](https://issues.jenkins-ci.org/browse/JENKINS-42280).
