### ISSUE TITLE
jenkins_password_credentials - unable to resolve class SchemeRequirement

### ISSUE THREAD

**Issue by zaiddabaeen** [chef-cookbooks/jenkins#568]
### Cookbook version
4.2.1

### Chef-client version
12.18.31

### Platform Details
Ubuntu 16.04 64 bit server

### Scenario:
Add a password credentials to jenkins. Provisioned by Chef in Vagrant.

### Steps to Reproduce:
Recipe as such:

```
include_recipe 'jenkins::master'
node.normal['jenkins']['master']['jvm_options'] = '-Djenkins.install.runSetupWizard=false'

jenkins_password_credentials 'admin' do
  id          'admin'
  description 'Admin'
  password    'admin'
end

service 'jenkins' do
  action [:enable, :start]
end
```

Note that jenkins installed is:

```
vagrant@local:~$ sudo apt-cache policy jenkins
jenkins:
  Installed: 2.47
  Candidate: 2.47
  Version table:
 *** 2.47 500
        500 http://pkg.jenkins-ci.org/debian binary/ Packages
        100 /var/lib/dpkg/status
```

Log stack:

```
==> default: (new content is binary, diff output suppressed)
==> default: [2017-02-21T12:50:32+00:00] INFO: remote_file[/var/chef/cache/jenkins-cli.jar] mode changed to 755
==> default:       
==> default: - change mode from '' to '0755'
==> default: 
==> default: 
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'jenkins_password_credentials[admin]'
==> default:     ================================================================================
==> default:     
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     Expected process to exit with [0], but received '1'
==> default:     ---- Begin output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170221-1963-1j72aef ----
==> default:     STDOUT: 
==> default:     STDERR: ERROR: Unexpected exception occurred while performing groovy command.
==> default:     org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
==> default:     RemoteClass: 15: unable to resolve class SchemeRequirement 
==> default:      @ line 15, column 13.
==> default:                    new SchemeRequirement("ssh")
==> default:                    ^
==> default:     
==> default:     1 error
==> default:     
==> default:     	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
==> default:     	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
==> default:     	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
==> default:     	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
==> default:     	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
==> default:     	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
==> default:     	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
==> default:     	at groovy.lang.GroovyShell.run(GroovyShell.java:517)
==> default:     	at groovy.lang.GroovyShell.run(GroovyShell.java:497)
==> default:     
==> default: 	at hudson.cli.GroovyCommand.run(GroovyCommand.java:89)
==> default:     	at hudson.cli.CLICommand.main(CLICommand.java:265)
==> default:     	at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:93)
==> default:     
==> default: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
==> default:     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
==> default:     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
==> default:     	at java.lang.reflect.Method.invoke(Method.java:498)
==> default:     	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:895)
==> default:     	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:870)
==> default:     	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:829)
==> default:     	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
==> default:     	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
==> default:     	at hudson.remoting.Request$2.run(Request.java:336)
==> default:     
==> default: 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
==> default:     	at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:64)
==> default:     	at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
==> default:     	at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
==> default:     	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
==> default:     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
==> default:     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
==> default:     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
==> default:     	at java.lang.Thread.run(Thread.java:745)
==> default:     ---- End output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170221-1963-1j72aef ----
==> default:     Ran "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170221-1963-1j72aef returned 1
==> default:     
==> default: 
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:85:in `execute!'
==> default:     
==> default: /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:138:in `groovy!'
==> default:     /var/chef/cache/cookbooks/jenkins/libraries/credentials.rb:227:in `current_credentials'
==> default:     /var/chef/cache/cookbooks/jenkins/libraries/credentials.rb:68:in `load_current_resource'
==> default:     /var/chef/cache/cookbooks/jenkins/libraries/credentials_user.rb:38:in `load_current_resource'
==> default:     /var/chef/cache/cookbooks/jenkins/libraries/credentials_password.rb:47:in `load_current_resource'
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     suppressed sensitive resource output
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     suppressed sensitive resource output
==> default:     
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux

```
### Expected Result:
A credentials user to be added

### Actual Result:
Error because `unable to resolve class SchemeRequirement `

**Comment by cheeseplus** [comment]
You need to install the credentials plugin for 2.x as it's not provided in core anymore. Note here https://github.com/chef-cookbooks/jenkins#jenkins_credentials and we've illustrated it with the latest released version's test cookbook https://github.com/chef-cookbooks/jenkins/blob/master/test/fixtures/cookbooks/jenkins_server_wrapper/recipes/default.rb
