### ISSUE TITLE
Error executing action `install` on resource 'jenkins_plugin[postbuildscript]'

### ISSUE THREAD

**Issue by ankitgupta07** [chef-cookbooks/jenkins#606]
### Cookbook version
Jenkins cookbook, version 5.0

### Chef-client version
Chef Client, version 12.12.15

### Platform Details
CentOS 6.8

### Scenario:
chef converge is failing while installing the "postbuildscript" plugin with below stack trace -

```  * jenkins_plugin[postbuildscript] action install
 ================================================================================
    Error executing action `install` on resource 'jenkins_plugin[postbuildscript]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:246:in `desired_version'
    /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:142:in `block in <class:JenkinsPlugin>'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------

     20:   jenkins_plugin plugin do
     21:     if ver == false
     22:       action :uninstall
     23:     else
     24:       version ver unless ver == true
     25:     end
     26:
```

### Steps to Reproduce:
If you add a step to install postbuildscript plugin, you would run into this issue

### Expected Result:
Chef should converge successfully.

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
Chef converge will fail at the "install plugin" stage

```  * jenkins_plugin[postbuildscript] action install
 ================================================================================
    Error executing action `install` on resource 'jenkins_plugin[postbuildscript]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:246:in `desired_version'
    /var/chef/cache/cookbooks/jenkins/libraries/plugin.rb:142:in `block in <class:JenkinsPlugin>'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------

     20:   jenkins_plugin plugin do
     21:     if ver == false
     22:       action :uninstall
     23:     else
     24:       version ver unless ver == true
     25:     end
     26:
```

**Comment by iennae** [comment]
This is the error you will get if the plugin isn't available. This looks to be a deprecated plugin based on it's lack of availability on https://plugins.jenkins.io/.
