### ISSUE TITLE
Error executing action `install` on resource 'jenkins_plugin[ansicolor]'

### ISSUE THREAD

**Issue by gomteshhatginecognologix** [chef-cookbooks/jenkins#632]
### Cookbook version
[Jenkins cookbook 2.4.1]

### Chef-client version
[chef-client version: 12.21.2]

### Platform Details
[Vagrant centos]

### Scenario:
[I want to install list of plugins after installation of Jenkins]

### Steps to Reproduce:
[
jenkins_plugin 'ace-editor'
jenkins_plugin 'analysis-core'
jenkins_plugin 'ansicolor'
jenkins_plugin 'antisamy-markup-formatter'

jenkins_command 'restart'
]

### Expected Result:
[Jenkins plugins list should installed]

### Actual Result:
[ ================================================================================
    Error executing action `install` on resource 'jenkins_plugin[ansicolor]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '6'
    ---- Begin output of "java" -jar "/root/.chef/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /root/.chef/local-mode-cache/cache/ansicolor-0.5.0.plugin -name ansicolor  ----
    STDOUT: 
    STDERR: ERROR: anonymous is missing the Overall/Read permission
    Jun 27, 2017 11:55:45 AM hudson.cli.CLI$5 run
    WARNING: null
    java.io.IOException: Stream is closed
    	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3512)
    	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3486)
    	at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
    	at hudson.cli.PlainCLIProtocol$EitherSide.send(PlainCLIProtocol.java:175)
    	at hudson.cli.PlainCLIProtocol$ClientSide.sendEndStdin(PlainCLIProtocol.java:347)
    	at hudson.cli.CLI$5.run(CLI.java:679)
    ---- End output of "java" -jar "/root/.chef/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /root/.chef/local-mode-cache/cache/ansicolor-0.5.0.plugin -name ansicolor  ----
    Ran "java" -jar "/root/.chef/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /root/.chef/local-mode-cache/cache/ansicolor-0.5.0.plugin -name ansicolor  returned 6
    
    Cookbook Trace:
    ---------------
    /root/.chef/local-mode-cache/cache/cookbooks/jenkins/libraries/_executor.rb:84:in `execute!'
    /root/.chef/local-mode-cache/cache/cookbooks/jenkins/libraries/plugin.rb:316:in `install_plugin_from_url'
    /root/.chef/local-mode-cache/cache/cookbooks/jenkins/libraries/plugin.rb:288:in `install_plugin_from_update_center'
    /root/.chef/local-mode-cache/cache/cookbooks/jenkins/libraries/plugin.rb:123:in `block (2 levels) in <class:JenkinsPlugin>'
    /root/.chef/local-mode-cache/cache/cookbooks/jenkins/libraries/plugin.rb:153:in `block in <class:JenkinsPlugin>'
    
    Resource Declaration:
    ---------------------
    # In /root/.chef/local-mode-cache/cache/cookbooks/jenkins/recipes/_master_package.rb
    
    102: jenkins_plugin 'ansicolor'
    103: # jenkins_plugin 'antisamy-markup-formatter'
    
    Compiled Resource:
    ------------------
    # Declared in /root/.chef/local-mode-cache/cache/cookbooks/jenkins/recipes/_master_package.rb:102:in `from_file'
    
    jenkins_plugin("ansicolor") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :jenkins_plugin
      cookbook_name "jenkins"
      recipe_name "_master_package"
    end
    
    System Info:
    ------------
    chef_version=12.21.2
    platform=centos
    platform_version=7.2.1511
    ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    program_name=chef-client worker: ppid=19601;start=11:55:33;
    executable=/opt/chefdk/bin/chef-client
    
[2017-06-27T11:55:45+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-06-27T11:55:45+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-06-27T11:55:45+00:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 12 seconds
[2017-06-27T11:55:45+00:00] FATAL: Stacktrace dumped to /root/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-06-27T11:55:45+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-06-27T11:55:45+00:00] ERROR: jenkins_plugin[ansicolor] (jenkins::_master_package line 102) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '6'
---- Begin output of "java" -jar "/root/.chef/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /root/.chef/local-mode-cache/cache/ansicolor-0.5.0.plugin -name ansicolor  ----
STDOUT: 
STDERR: ERROR: anonymous is missing the Overall/Read permission
Jun 27, 2017 11:55:45 AM hudson.cli.CLI$5 run
WARNING: null
java.io.IOException: Stream is closed
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3512)
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3486)
	at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
	at hudson.cli.PlainCLIProtocol$EitherSide.send(PlainCLIProtocol.java:175)
	at hudson.cli.PlainCLIProtocol$ClientSide.sendEndStdin(PlainCLIProtocol.java:347)
	at hudson.cli.CLI$5.run(CLI.java:679)
---- End output of "java" -jar "/root/.chef/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /root/.chef/local-mode-cache/cache/ansicolor-0.5.0.plugin -name ansicolor  ----
Ran "java" -jar "/root/.chef/local-mode-cache/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /root/.chef/local-mode-cache/cache/ansicolor-0.5.0.plugin -name ansicolor  returned 6
[2017-06-27T11:55:45+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
]

**Comment by tas50** [comment]
It looks like you're not setting your authentication details and the plugin installation fails as anonymous users cannot install plugins. Make your correctly authenticated and open this back up if you're still having issues.

**Comment by gomteshhatginecognologix** [comment]
Where is the backup??

**Comment by StephenKing** [comment]
He meant that you should open this issue again, if you have trouble. Nothing about backing up data.

**Comment by gomteshhatginecognologix** [comment]
I cannot re-open my own issues if a repo collaborator closed them
