### ISSUE TITLE
Issue installing plugins when SSL is configured

### ISSUE THREAD

**Issue by jharshman** [chef-cookbooks/jenkins#655]
### Cookbook version
5.0.3

### Chef-client version
12.11.18

### Platform Details
Ubuntu Trusty64

### Scenario:
Install plugins after securing Jenkins with SSL certificates.

### Steps to Reproduce:
Configure SSL on Jenkins:
``` ruby
bag = data_bag_item(node['example-jenkins']['master']['data_bag'], 'master')

node.run_state['keystore-password'] = bag['keystore-password']
node.run_state['wildcardkey-pem']   = bag['wildcardkey-pem']
node.run_state['wildcard-pem']      = bag['wildcard-pem']

directory "#{node['example-jenkins']['master']['home']}/ssl" do
  owner node['example-jenkins']['master']['user']
  group node['example-jenkins']['master']['group']
  mode '0755'
  action :create
end

file "#{node['example-jenkins']['master']['home']}/ssl/wildcardkey.pem" do
  content node.run_state['wildcardkey-pem']
  owner node['example-jenkins']['master']['user']
  group node['example-jenkins']['master']['group']
  mode '0755'
  action :create
end

file "#{node['example-jenkins']['master']['home']}/ssl/wildcard.pem" do
  content node.run_state['wildcard-pem']
  owner node['example-jenkins']['master']['user']
  group node['example-jenkins']['master']['group']
  mode '0755'
  action :create
end

bash 'generate key store' do
  cwd "#{node['example-jenkins']['master']['home']}/ssl"
  code <<-EOH
    openssl pkcs12 \
      -inkey wildcardkey.pem \
      -in wildcard.pem \
      -export \
      -password pass:#{node.run_state['keystore-password']} \
      -out keys.pkcs12

    keytool \
      -importkeystore \
      -srckeystore keys.pkcs12 \
      -srcstoretype pkcs12 \
      -srcstorepass #{node.run_state['keystore-password']} \
      -deststorepass #{node.run_state['keystore-password']} \
      -destkeystore jenkins.jks
  EOH
  not_if { ::File.exists?("#{node['example-jenkins']['master']['home']}/ssl/jenkins.jks") }
end

template '/etc/default/jenkins' do
  source 'jenkins-conf.erb'
  mode '0644'
end
```
jenkins-conf.erb snippet
``` ruby
... snip

# SSL Params
HTTPS_PORT=<%= node['jenkins']['master']['port'] %> # default should be 8043
KeyStorePath=<%= node['example-jenkins']['master']['keystore-path'] %> # Default should be $JENKINS_HOME/ssl/jenkins.jks
KeyStorePass=<%= node.run_state['keystore-password'] %>

JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpsPort=$HTTPS_PORT --httpsKeyStore=$KeyStorePath --httpsKeyStorePassword=$KeyStorePass"
```

Try to install plugins:
``` ruby
plugin_list = node['example-jenkins']['master']['plugins']
plugin_list.each_with_index do |(plugin, ver), index|
  jenkins_plugin plugin do
    version ver
    install_deps true
    action :install
    if index == (plugin_list.size - 1)
      notifies node['example-jenkins']['master']['change-notify'], 'service[jenkins]', :immediately
    end
  end
end
```

### Expected Result:
Plugins install

### Actual Result:
Converge fails on plugin install.

``` bash
================================================================================
           Error executing action `install` on resource 'jenkins_plugin[greenballs]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '255'
           ---- Begin output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s https://default-ubuntu-trusty64.example.us:8043 -"remoting" install-plugin file:///tmp/kitchen/cache/greenballs-1.15.plug
in -name greenballs  ----
           STDOUT:
           STDERR: java.io.IOException: Failed to connect to https://default-ubuntu-trusty64.example.us:8043/
                at hudson.cli.CLI.getCliTcpPort(CLI.java:296)
                at hudson.cli.CLI.<init>(CLI.java:137)
                at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:82)
                at hudson.cli.CLI._main(CLI.java:593)
                at hudson.cli.CLI.main(CLI.java:407)
                Suppressed: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
                        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
                        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
                        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
                        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1899)
                        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
                        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
                        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
                        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
                        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
                        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
                        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
                        at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:98)
                        at hudson.cli.CLI.connectViaHttp(CLI.java:163)
                        at hudson.cli.CLI.<init>(CLI.java:141)
                        ... 3 more
```

**Comment by jharshman** [comment]
Resolved.  Issue was `ca-certificates-java` was not present.
