### ISSUE TITLE
master_package.rb contains cloned directory resource

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/jenkins#679]
### Cookbook version
5.0.6

### Chef-client version
chefdk 2.4.17

### Platform Details
Test Kitchen run: RHEL6 running in an openstack VM

### Scenario:
chef run reports this:

```
[2018-02-03T12:48:47-08:00] WARN: Cloning resource attributes for directory[/var/lib/jenkins] from prior resource
Previous directory[/var/lib/jenkins]: /tmp/chefspec20180203-11484-7ci1e3file_cache_path/cookbooks/jenkins/recipes/_master_package.rb:51:in `from_file'
Current  directory[/var/lib/jenkins]: /tmp/chefspec20180203-11484-7ci1e3file_cache_path/cookbooks/jenkins/recipes/_master_package.rb:68:in `block in from_file' (CHEF-3694)/tmp/chefspec20180203-11484-7ci1e3file_cache_path/cookbooks/jenkins/recipes/_master_package.rb:68:in `block in from_file'.
Please see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at /var/cache/jenkins/bundler/ruby/2.4.0/gems/chef-12.21.31/lib/chef/event_dispatch/dispatcher.rb:43:in `call'

```

### Steps to Reproduce:
We've wrapped the jenkins cookbook and our recipe is running `include_recipe 'jenkins::master'`

**Comment by marcmillien** [comment]
Hi @haidangwa , your issue has been solved :). You can close it.
