### ISSUE TITLE
runit_service errors when using Chef 14

### ISSUE THREAD

**Issue by fletchowns** [chef-cookbooks/jenkins#686]
### Cookbook version
6.0.0

### Chef-client version
14.0.202

### Platform Details
Redhat 7.5 on AWS (ami-18726478)

### Scenario:
WAR file based install of Jenkins 2.120

### Steps to Reproduce:
I am using the following attributes:
```
default["jenkins"]["executor"]["timeout"] = 240
default["jenkins"]["master"]["install_method"] = "war"
default["jenkins"]["master"]["version"] = "2.120"
```

### Expected Result:
Converge should be successful, the same configuration works fine on Chef 12, but fails on Chef 14.

### Actual Result:
```
       Recipe: runit::default
         * packagecloud_repo[imeyer/runit] action add
           * yum_package[pygpgme] action install (up to date)
           * log[pygpgme_warning] action write (skipped due to not_if)
           * ruby_block[disable repo_gpgcheck if no pygpgme] action run (skipped due to not_if)
           * template[/etc/yum.repos.d/imeyer_runit.repo] action create
             - create new file /etc/yum.repos.d/imeyer_runit.repo
             - update content in file /etc/yum.repos.d/imeyer_runit.repo from none to 77af55
             --- /etc/yum.repos.d/imeyer_runit.repo     2018-05-18 21:40:09.495135134 +0000
             +++ /etc/yum.repos.d/.chef-imeyer_runit20180518-9911-1svhj6s.repo  2018-05-18 21:40:09.495135134 +0000
             @@ -1 +1,11 @@
             +[imeyer_runit]
             +name=imeyer_runit
             +baseurl=https://packagecloud.io/imeyer/runit/el/7/$basearch
             +repo_gpgcheck=1
             +gpgcheck=0
             +enabled=1
             +gpgkey=https://packagecloud.io/imeyer/runit/gpgkey
             +sslverify=1
             +sslcacert=/etc/pki/tls/certs/ca-bundle.crt
             +metadata_expire=300
             - change mode from '' to '0644'
             - restore selinux security context
           * execute[yum-makecache-imeyer_runit] action run
             - execute yum -q makecache -y --disablerepo=* --enablerepo=imeyer_runit
           * ruby_block[yum-cache-reload-imeyer_runit] action run
             - execute the ruby block yum-cache-reload-imeyer_runit
           * execute[yum-makecache-imeyer_runit] action nothing (skipped due to action :nothing)
           * ruby_block[yum-cache-reload-imeyer_runit] action nothing (skipped due to action :nothing)

         * yum_package[runit] action install
           - install version 0:2.1.2-3.el7.centos.x86_64 of package runit
         * service[runsvdir-start] action start (up to date)
         * service[runsvdir-start] action enable (up to date)
       Recipe: jenkins::_master_war
         * remote_file[/var/lib/jenkins/jenkins.war] action create
           - create new file /var/lib/jenkins/jenkins.war
           - update content in file /var/lib/jenkins/jenkins.war from none to 439787
           (file sizes exceed 10000000 bytes, diff output suppressed)
           - change owner from '' to 'jenkins'
           - change group from '' to 'jenkins'
           - restore selinux security context
       Recipe: <Dynamically Defined Resource>
         * service[jenkins] action nothing (skipped due to action :nothing)
       Recipe: jenkins::_master_war
         * runit_service[jenkins] action enable
           * ruby_block[restart_service] action nothing (skipped due to action :nothing)
           * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
           * directory[/etc/sv/jenkins] action create
             - create new directory /etc/sv/jenkins
             - change mode from '' to '0755'
             - restore selinux security context
           * template[/etc/sv/jenkins/run] action create
             - create new file /etc/sv/jenkins/run
             - update content in file /etc/sv/jenkins/run from none to 88d9dc
             --- /etc/sv/jenkins/run    2018-05-18 21:40:15.673500926 +0000
             +++ /etc/sv/jenkins/.chef-run20180518-9911-1nct5we 2018-05-18 21:40:15.673500926 +0000
             @@ -1 +1,20 @@
             +#!/bin/sh
             +
             +#
             +# This file was generated by Chef.
             +# Do NOT modify this file by hand.
             +#
             +
             +[ -r /etc/profile ] && . /etc/profile
             +
             +exec 2>&1
             +cd /var/lib/jenkins
             +touch jenkins.start
             +exec chpst -u jenkins: -U jenkins: \
             +  env HOME=/var/lib/jenkins \
             +  JENKINS_HOME=/var/lib/jenkins \
             +  java -Dmail.smtp.starttls.enable=true -Djenkins.install.runSetupWizard=false -jar jenkins.war \
             +  --httpPort=8080 \
             +  --httpListenAddress=0.0.0.0 \
             +
             - change mode from '' to '0755'
             - restore selinux security context
           * directory[/etc/sv/jenkins/log] action create
             - create new directory /etc/sv/jenkins/log
             - restore selinux security context
           * directory[/etc/sv/jenkins/log/main] action create
             - create new directory /etc/sv/jenkins/log/main
             - change mode from '' to '0755'
             - restore selinux security context
           * directory[/var/log/jenkins] action create (up to date)
           * template[/etc/sv/jenkins/log/config] action create
             - create new file /etc/sv/jenkins/log/config
             - update content in file /etc/sv/jenkins/log/config from none to e3b0c4
             (no diff)
             - change mode from '' to '0644'
             - restore selinux security context
           * link[/var/log/jenkins/config] action create
             - create symlink at /var/log/jenkins/config to /etc/sv/jenkins/log/config
           * template[/etc/sv/jenkins/log/run] action create
             - create new file /etc/sv/jenkins/log/run
             - update content in file /etc/sv/jenkins/log/run from none to d76c77
             --- /etc/sv/jenkins/log/run        2018-05-18 21:40:15.785489431 +0000
             +++ /etc/sv/jenkins/log/.chef-run20180518-9911-149rexl     2018-05-18 21:40:15.784489533 +0000
             @@ -1 +1,9 @@
             +#!/bin/sh
             +
             +#
             +# This file was generated by Chef.
             +# Do NOT modify this file by hand.
             +#
             +
             +exec chpst -unobody logger -d -p local6.info -t [jenkins]
             - change mode from '' to '0755'
             - restore selinux security context
           * directory[/etc/sv/jenkins/env] action create
             - create new directory /etc/sv/jenkins/env
             - change mode from '' to '0755'
             - restore selinux security context
           * ruby_block[Delete unmanaged env files for jenkins service] action run (skipped due to only_if)
           * template[/etc/sv/jenkins/check] action create (skipped due to only_if)
           * template[/etc/sv/jenkins/finish] action create (skipped due to only_if)
           * directory[/etc/sv/jenkins/control] action create
             - create new directory /etc/sv/jenkins/control
             - change mode from '' to '0755'
             - restore selinux security context
           * link[/etc/init.d/jenkins] action create
             - create symlink at /etc/init.d/jenkins to /sbin/sv
           * file[/etc/sv/jenkins/down] action nothing (skipped due to action :nothing)
           * ruby_block[restart_service] action run
             * ruby_block[restart_service] action nothing (skipped due to action :nothing)
             * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
             * directory[/etc/sv/jenkins] action create (up to date)
             * template[/etc/sv/jenkins/run] action create (up to date)
             * directory[/etc/sv/jenkins/log] action create (up to date)
             * directory[/etc/sv/jenkins/log/main] action create (up to date)
             * directory[/var/log/jenkins] action create (up to date)
             * template[/etc/sv/jenkins/log/config] action create (up to date)
             * link[/var/log/jenkins/config] action create (up to date)
             * template[/etc/sv/jenkins/log/run] action create (up to date)
             * directory[/etc/sv/jenkins/env] action create (up to date)
             * ruby_block[Delete unmanaged env files for jenkins service] action run (skipped due to only_if)
             * template[/etc/sv/jenkins/check] action create (skipped due to only_if)
             * template[/etc/sv/jenkins/finish] action create (skipped due to only_if)
             * directory[/etc/sv/jenkins/control] action create (up to date)
             * link[/etc/init.d/jenkins] action create (up to date)
             * file[/etc/sv/jenkins/down] action nothing (skipped due to action :nothing)
             * directory[/etc/service] action create (up to date)
             * link[/etc/service/jenkins] action create
        - create symlink at /etc/service/jenkins to /etc/sv/jenkins
             * ruby_block[wait for jenkins service socket] action run
        - execute the ruby block wait for jenkins service socket

             ================================================================================
             Error executing action `run` on resource 'ruby_block[restart_service]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of /sbin/sv -w '7' restart /etc/service/jenkins ----
             STDOUT: timeout: down: /etc/service/jenkins: 1s, normally up, want up
             STDERR:
             ---- End output of /sbin/sv -w '7' restart /etc/service/jenkins ----
             Ran /sbin/sv -w '7' restart /etc/service/jenkins returned 1

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
             /tmp/kitchen/cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
             /tmp/kitchen/cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
             /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:56:in `block (3 levels) in <class:RunitService>'
             /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:282:in `block in <class:RunitService>'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb

       53:         ruby_block 'restart_service' do
       54:           block do
       55:             action_enable
       56:             restart_service
       57:           end
       58:           action :nothing
       59:           only_if { new_resource.restart_on_update && !new_resource.start_down }
       60:         end
       61:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:53:in `block in <class:RunitService>'

             ruby_block("restart_service") do
        action [:nothing]
        default_guard_interpreter :default
        declared_type :ruby_block
        cookbook_name "jenkins"
        block #<Proc:0x0000000006b0a508@/tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:54>
        block_name "restart_service"
        only_if { #code block }
             end

             System Info:
             ------------
             chef_version=14.0.202
             platform=redhat
             platform_version=7.5
             ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
             program_name=/opt/chef/bin/chef-client
             executable=/opt/chef/bin/chef-client

           * ruby_block[restart_log_service] action run
             * ruby_block[restart_service] action nothing (skipped due to action :nothing)
             * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
             * directory[/etc/sv/jenkins] action create (up to date)
             * template[/etc/sv/jenkins/run] action create (up to date)
             * directory[/etc/sv/jenkins/log] action create (up to date)
             * directory[/etc/sv/jenkins/log/main] action create (up to date)
             * directory[/var/log/jenkins] action create (up to date)
             * template[/etc/sv/jenkins/log/config] action create (up to date)
             * link[/var/log/jenkins/config] action create (up to date)
             * template[/etc/sv/jenkins/log/run] action create (up to date)
             * directory[/etc/sv/jenkins/env] action create (up to date)
             * ruby_block[Delete unmanaged env files for jenkins service] action run (skipped due to only_if)
             * template[/etc/sv/jenkins/check] action create (skipped due to only_if)
             * template[/etc/sv/jenkins/finish] action create (skipped due to only_if)
             * directory[/etc/sv/jenkins/control] action create (up to date)
             * link[/etc/init.d/jenkins] action create (up to date)
             * file[/etc/sv/jenkins/down] action nothing (skipped due to action :nothing)
             * directory[/etc/service] action create (up to date)
             * link[/etc/service/jenkins] action create (up to date)
             * ruby_block[wait for jenkins service socket] action run
        - execute the ruby block wait for jenkins service socket
             - execute the ruby block restart_log_service

           ================================================================================
           Error executing action `enable` on resource 'runit_service[jenkins]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           ruby_block[restart_service] (/tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of /sbin/sv -w '7' restart /etc/service/jenkins ----
           STDOUT: timeout: down: /etc/service/jenkins: 1s, normally up, want up
           STDERR:
           ---- End output of /sbin/sv -w '7' restart /etc/service/jenkins ----
           Ran /sbin/sv -w '7' restart /etc/service/jenkins returned 1

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
           /tmp/kitchen/cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
           /tmp/kitchen/cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
           /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:56:in `block (3 levels) in <class:RunitService>'
           /tmp/kitchen/cache/cookbooks/runit/libraries/provider_runit_service.rb:282:in `block in <class:RunitService>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/jenkins/recipes/_master_war.rb

            70: runit_service 'jenkins' do
            71:   sv_timeout node['jenkins']['master']['runit']['sv_timeout']
            72: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/jenkins/recipes/_master_war.rb:70:in `from_file'

           runit_service("jenkins") do
             provider Chef::Provider::RunitService
             action :enable
             updated true
             updated_by_last_action true
             default_guard_interpreter :default
             service_name "jenkins"
             enabled false
             running false
             masked nil
             pattern "jenkins"
             status_command "/sbin/sv status /etc/service"
             supports {:restart=>true, :reload=>true, :status=>true}
             sv_bin "/sbin/sv"
             sv_dir "/etc/sv"
             service_dir "/etc/service"
             lsb_init_dir "/etc/init.d"
             log true
             restart_on_update true
             run_template_name "jenkins"
             log_template_name "jenkins"
             check_script_template_name "jenkins"
             finish_script_template_name "jenkins"
             sv_templates true
             sv_timeout 7
             log_dir "/var/log/jenkins"
             service_mirror # Declared in

           service("jenkins") do
             provider Chef::Provider::Service::Simple
             action [:nothing]
             default_guard_interpreter :default
             service_name "jenkins"
             enabled nil
             running nil
             masked nil
             pattern "jenkins"
             start_command "/sbin/sv start /etc/service/jenkins"
             stop_command "/sbin/sv stop /etc/service/jenkins"
             status_command "/sbin/sv status /etc/service/jenkins"
             restart_command "/sbin/sv restart /etc/service/jenkins"
             supports {:restart=>true, :reload=>true, :status=>true}
           end

             declared_type :runit_service
             cookbook_name "jenkins"
             recipe_name "_master_war"
           end

           System Info:
           ------------
           chef_version=14.0.202
           platform=redhat
           platform_version=7.5
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
```

**Comment by fletchowns** [comment]
I encountered the same issue on Chef 13, as well as 12.22.5-1

**Comment by fletchowns** [comment]
Here's the changes it makes to `/etc/sv/jenkins/run` when going from Chef 12 -> Chef 14, which ends up causing the jenkins service to not be able to start:
```
Recipe: jenkins::_master_war
  * runit_service[jenkins] action enable
    * ruby_block[restart_service] action nothing (skipped due to action :nothing)
    * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
    * directory[/etc/sv/jenkins] action create (up to date)
    * template[/etc/sv/jenkins/run] action create
      - update content in file /etc/sv/jenkins/run from a2893d to 88d9dc
      --- /etc/sv/jenkins/run	2018-08-18 01:35:30.579834161 +0000
      +++ /etc/sv/jenkins/.chef-run20181009-8299-172016f	2018-10-09 17:48:43.302170583 +0000
      @@ -1,15 +1,16 @@
       #!/bin/sh
       
       #
      -# This file was generated by Chef for jenkins.myorg.com.
      +# This file was generated by Chef.
       # Do NOT modify this file by hand.
       #
       
      +[ -r /etc/profile ] && . /etc/profile
       
       exec 2>&1
       cd /var/lib/jenkins
       touch jenkins.start
      -exec chpst -u jenkins:jenkins:tomcat -U jenkins:jenkins:tomcat \
      +exec chpst -u jenkins: -U jenkins: \
         env HOME=/var/lib/jenkins \
         JENKINS_HOME=/var/lib/jenkins \
         java -Dmail.smtp.starttls.enable=true -Djenkins.install.runSetupWizard=false -jar jenkins.war \
      - restore selinux security context
    * directory[/etc/sv/jenkins/log] action create (up to date)
    * directory[/etc/sv/jenkins/log/main] action create (up to date)
    * directory[/var/log/jenkins] action create (up to date)
    * template[/etc/sv/jenkins/log/config] action create (up to date)
    * link[/var/log/jenkins/config] action create (up to date)
    * template[/etc/sv/jenkins/log/run] action create
      - update content in file /etc/sv/jenkins/log/run from f861dd to d76c77
      --- /etc/sv/jenkins/log/run	2018-08-18 01:35:30.631834289 +0000
      +++ /etc/sv/jenkins/log/.chef-run20181009-8299-1nbykdj	2018-10-09 17:48:43.350170718 +0000
      @@ -1,7 +1,7 @@
       #!/bin/sh
       
       #
      -# This file was generated by Chef for jenkins.myorg.com.
      +# This file was generated by Chef.
       # Do NOT modify this file by hand.
       #
       
      - restore selinux security context
```

Perhaps it is only reproducible if the jenkins service user is a member of multiple groups? @tas50 any ideas on this one?

**Comment by fletchowns** [comment]
Also saw some entries in my `/var/log/messages` when the runit service was failing to start:
```
Oct  9 18:49:35 jenkins [jenkins]: chpst: fatal: unknown user/group: jenkins:
Oct  9 18:49:36 jenkins [jenkins]: chpst: fatal: unknown user/group: jenkins:
Oct  9 18:49:37 jenkins [jenkins]: chpst: fatal: unknown user/group: jenkins:
Oct  9 18:49:38 jenkins [jenkins]: chpst: fatal: unknown user/group: jenkins:
Oct  9 18:49:39 jenkins [jenkins]: chpst: fatal: unknown user/group: jenkins:
```

**Comment by fletchowns** [comment]
I am no longer running into this issue with runit cookbook 5.1.0 and jenkins cookbook 7.0.0
